// Golden comparison against hledger-CLI output (fixtures/golden/, generated by
// scripts/gen-golden.sh from fixtures/sample.journal). Input comes from the
// RAW API snapshot (fixtures/api/v1.52/) through the normalizer — the same
// path production data takes.
//
// Date reconciliation: hledger's `-e DATE` is EXCLUSIVE, our asOf/to are
// INCLUSIVE, so `-e 2026-07-01` ≙ asOf/to "2026-06-30".
//
// Amount reconciliation: hledger keeps same-commodity amounts with different
// cost bases as separate MixedAmount entries (three AAPL lots, three EUR
// lots); our MixedAmount merges per commodity. The adapter therefore sums the
// golden amounts per commodity with exact Dec math and compares canonical
// mantissa/places (trailing zeros stripped, e.g. 657.4300 ≡ 657.43 — hledger
// normalizes its decimals). Never floats.

import {readFileSync} from "node:fs";
import {describe, expect, it} from "vitest";
import {normalizeAccounts, normalizePrices, normalizeTransactions} from "../api/normalize";
import {cashPredicate} from "../domain/accountTypes";
import {add, dec, type Dec, type MixedAmount} from "../domain/money";
import {balanceSheet} from "./balanceSheet";
import {cashFlow} from "./cashFlow";
import {incomeStatement} from "./incomeStatement";
import {netWorth} from "./netWorth";
import {buildPriceDb} from "./prices";
import type {SectionedReport} from "./types";

// ---- fixtures (repo root is four levels above src/lib/reports/) ----

const fixture = (rel: string): unknown => JSON.parse(readFileSync(new URL(`../../../../fixtures/${rel}`, import.meta.url), "utf8"));

const txns = normalizeTransactions(fixture("api/v1.52/transactions.json"));
const priceDb = buildPriceDb(normalizePrices(fixture("api/v1.52/prices.json")));
const accountDecls = normalizeAccounts(fixture("api/v1.52/accounts.json"));

// ---- minimal shapes of hledger's report JSON (adapter-local; NOT our domain) ----

interface GAmount {
    acommodity: string;
    aquantity: {decimalMantissa: number; decimalPlaces: number};
}
interface GRow {
    prrName: string;
    prrAmounts: GAmount[][];
}
interface GSubreport {
    prRows: GRow[];
    prTotals: GRow;
}
interface GCompound {
    cbrSubreports: [string, GSubreport][];
    cbrTotals: GRow;
}
type GBalRow = [string, string, number, GAmount[]];
type GBalReport = [GBalRow[], GAmount[]];

// ---- canonical exact comparison: {commodity → {mantissa, places}}, trailing zeros stripped ----

function canon(d: Dec): {m: bigint; p: number} {
    let {m, p} = d;
    while (p > 0 && m % 10n === 0n) {
        m /= 10n;
        p -= 1;
    }
    return {m, p};
}

function canonMap(ma: MixedAmount): Record<string, {m: bigint; p: number}> {
    const out: Record<string, {m: bigint; p: number}> = {};
    for (const [commodity, qty] of ma) {
        const c = canon(qty);
        if (c.m !== 0n) out[commodity] = c;
    }
    return out;
}

/** Sum hledger amounts per commodity (merging cost-basis lots) with exact Dec math. */
function sumGolden(amounts: GAmount[]): Record<string, {m: bigint; p: number}> {
    const ma: MixedAmount = new Map();
    for (const amount of amounts) {
        const qty = dec(amount.aquantity.decimalMantissa, amount.aquantity.decimalPlaces);
        const prev = ma.get(amount.acommodity);
        ma.set(amount.acommodity, prev === undefined ? qty : add(prev, qty));
    }
    return canonMap(ma);
}

/** A section's "leaves": rows that are not an ancestor of another row (what hledger's flat JSON lists). */
function leafAccounts(rows: {account: string}[]): string[] {
    return rows.filter((row) => !rows.some((other) => other.account.startsWith(row.account + ":"))).map((row) => row.account);
}

function checkSectioned(report: SectionedReport, golden: GCompound): void {
    for (const [title, sub] of golden.cbrSubreports) {
        const section = report.sections.find((s) => s.title === title);
        expect(section, `section ${title} exists`).toBeDefined();
        expect(leafAccounts(section!.rows).sort(), `${title} leaf account set`).toEqual(sub.prRows.map((r) => r.prrName).sort());
        for (const row of sub.prRows) {
            const mine = section!.rows.find((r) => r.account === row.prrName);
            expect(mine, `row ${row.prrName} exists`).toBeDefined();
            expect(canonMap(mine!.inclusive), `row ${row.prrName}`).toEqual(sumGolden(row.prrAmounts[0]));
        }
        expect(canonMap(section!.total), `${title} total`).toEqual(sumGolden(sub.prTotals.prrAmounts[0]));
    }
    expect(canonMap(report.grandTotal), "grand total").toEqual(sumGolden(golden.cbrTotals.prrAmounts[0]));
}

describe("GOLDEN reports vs hledger CLI", () => {
    it("balanceSheet matches `hledger bs --depth 1 -e 2026-07-01`", () => {
        checkSectioned(balanceSheet(txns, {asOf: "2026-06-30", depth: 1}), fixture("golden/bs-d1.json") as GCompound);
    });

    it("balanceSheet matches `hledger bs --depth 2 -e 2026-07-01` (CLI-derived, embedded)", () => {
        // No committed golden at depth 2; expectations generated once from
        // hledger 1.52 (same flags as gen-golden.sh, --depth 2) on 2026-07-13
        // after the WP-10 stock fixtures landed (NVDA nets to zero → dropped).
        const report = balanceSheet(txns, {asOf: "2026-06-30", depth: 2});
        const rows = Object.fromEntries(report.sections.flatMap((s) => s.rows.map((r) => [r.account, canonMap(r.inclusive)])));
        const stocks = {AAPL: {m: 195n, p: 1}, GLD: {m: 5n, p: 0}, TSLA: {m: -2n, p: 0}, VTI: {m: 17n, p: 0}};
        expect(rows["assets:bank"]).toEqual({$: {m: 4366781n, p: 2}, EUR: {m: 56675n, p: 2}});
        expect(rows["assets:broker"]).toEqual({$: {m: 660975n, p: 2}, ...stocks});
        expect(rows["liabilities:cc"]).toEqual({$: {m: 6211n, p: 2}});
        expect(canonMap(report.sections[0].total)).toEqual({$: {m: 5027756n, p: 2}, EUR: {m: 56675n, p: 2}, ...stocks});
        expect(canonMap(report.sections[1].total)).toEqual({$: {m: 6211n, p: 2}});
        expect(canonMap(report.grandTotal)).toEqual({$: {m: 5021545n, p: 2}, EUR: {m: 56675n, p: 2}, ...stocks});
    });

    it("balanceSheet matches `hledger bs --depth 3 -e 2026-07-01`", () => {
        checkSectioned(balanceSheet(txns, {asOf: "2026-06-30", depth: 3}), fixture("golden/bs-d3.json") as GCompound);
    });

    it("incomeStatement matches `hledger is -b 2026-01-01 -e 2026-07-01 --depth 2`", () => {
        checkSectioned(incomeStatement(txns, {from: "2026-01-01", to: "2026-06-30", depth: 2}), fixture("golden/is-d2.json") as GCompound);
    });

    // hledger's cashflow honors the `type: C` account declarations. We run our
    // engine both with the name-only fallback (default) and with the declared
    // predicate built from the real /accounts snapshot: both must reproduce
    // hledger's selection, proving the declared-type path is faithful.
    it.each([
        ["name heuristic (default)", undefined],
        ["declared /accounts types", cashPredicate(accountDecls)],
    ])("cashFlow matches `hledger cashflow -M -b 2026-01-01 -e 2026-07-01` — %s", (_label, isCash) => {
        const report = cashFlow(txns, {end: "2026-06-30", interval: "monthly", count: 6, depth: 99, isCash});
        expect(report.buckets).toEqual(["2026-01", "2026-02", "2026-03", "2026-04", "2026-05", "2026-06"]);

        const golden = fixture("golden/cf-monthly.json") as GCompound;
        const sub = golden.cbrSubreports[0][1];
        expect(leafAccounts(report.rows).sort()).toEqual(sub.prRows.map((r) => r.prrName).sort());
        for (const row of sub.prRows) {
            const mine = report.rows.find((r) => r.account === row.prrName);
            expect(mine, `row ${row.prrName} exists`).toBeDefined();
            for (let i = 0; i < report.buckets.length; i += 1) {
                expect(canonMap(mine!.values[i]), `${row.prrName} ${report.buckets[i]}`).toEqual(sumGolden(row.prrAmounts[i]));
            }
        }
        for (let i = 0; i < report.buckets.length; i += 1) {
            expect(canonMap(report.totals[i]), `totals ${report.buckets[i]}`).toEqual(sumGolden(sub.prTotals.prrAmounts[i]));
        }
    });

    it("netWorth matches `hledger bal --value=end,$ -e 2026-07-01 assets liabilities`", () => {
        const report = netWorth(txns, priceDb, {end: "2026-06-30", interval: "monthly", count: 1});
        // GLD and TSLA deliberately have no P directive (WP-10 fixtures):
        // hledger leaves them unvalued in place; our engine skips them and
        // reports them in meta.unpriced instead — filter them from the golden.
        const unpriced = ["GLD", "TSLA"];
        expect(report.meta, "exactly the deliberately unpriced commodities are skipped").toEqual({unpriced});
        const valued = (amounts: GAmount[]): GAmount[] => amounts.filter((amount) => !unpriced.includes(amount.acommodity));

        const [goldenRows, goldenTotal] = fixture("golden/networth-spot.json") as GBalReport;
        const byRoot = new Map<string, GAmount[]>();
        for (const [account, , , amounts] of goldenRows) {
            const root = account.split(":", 1)[0];
            byRoot.set(root, [...(byRoot.get(root) ?? []), ...amounts]);
        }
        expect(report.rows.map((r) => r.account).sort()).toEqual([...byRoot.keys()].sort());
        for (const [root, amounts] of byRoot) {
            const mine = report.rows.find((r) => r.account === root);
            expect(canonMap(mine!.values[0]), `valued ${root}`).toEqual(sumGolden(valued(amounts)));
        }
        expect(canonMap(report.totals[0]), "net worth").toEqual(sumGolden(valued(goldenTotal)));
    });
});
